<template>
    <div class="blog-page">
        <b-card>
            <h1>Create blogpost</h1>
            <div class="form mb-3">
                <b-form-input v-model="blogName" :state="blogState" placeholder="Your blog highlight"></b-form-input>
            </div>
        </b-card>
        <br />
        <b-card>
            <h1>Content creator</h1>

            <div class="editor-selector">
                <EditorElements :editor="editor" @img="getUrl" />
            </div>
            <br />
            <editor-content :editor="editor" />
        </b-card>
        <div>
            <b-modal title="Enter Image URL" v-model="showModal" @ok="handleImgUrl" :no-close-on-backdrop="true">
                <form ref="form" @submit.stop.prevent="handleImgUrl">
                    <b-form-group label="URL" label-for="img-url" invalid-feedback="URL is required" :state="imgUrlState">
                        <b-form-input id="img-url" v-model="imgUrl" required :state="imgUrlState"></b-form-input>
                    </b-form-group>
                </form>
            </b-modal>
        </div>
        <div class="text-center">
            <b-button variant="outline-primary" @click="createBlog">Finalize</b-button>
        </div>
    </div>
</template>

<script>
import EditorElements from './editorElements.vue'
import { Editor, EditorContent } from '@tiptap/vue-2'
import StarterKit from '@tiptap/starter-kit'
import TextAlign from '@tiptap/extension-text-align'
import Image from '@tiptap/extension-image'
import { Color } from '@tiptap/extension-color'
import TextStyle from '@tiptap/extension-text-style'

export default {
    name: "createBlog",
    components: {
        EditorContent, EditorElements
    },
    data() {
        return {
            editor: new Editor({
                content: `<h1 style="text-align:center;">The AI Blog</h1><hr/>
                <h2 style="text-align:center;"><p>Welcome to the testing on new blogpost</p></h2>
                <img src="https://colorwhistle.com/wp-content/uploads/2022/04/AI-Statistics-for-Small-Business.webp"/>
                <p><br>We love A.I. and welcome you to our AI blog. There is so much going on in the field of AI and our goal is to keep you up-to-date in innovative, informative, and entertaining ways. We see this website as a form of digital art as all images and text were generated by artificial intelligence (with a little bit of human help). Basically, this AI blog is written and designed by impressive AIs, and humans merely perform copy & paste operations - we showcase the progress of AI capabilities on all fronts (text, image, design, technology, education, etc).</p>
                <p>Some examples like</p>
                <ul><li><p> Ut enim ad minim veniam</p></li><li><p> quis nostrud exercitation ullamco</p></li><li><p> laboris nisi ut aliquip ex ea commodo </p></li><li><p>consequa</p></li></ul>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum</p>
                <h3 style="text-align: center"><i>you can add you content however you like</i></h3>
                `,
                extensions: [
                    StarterKit,
                    TextAlign.configure({
                        types: ['heading', 'paragraph'],
                    }),
                    Image,
                    TextStyle,
                    Color
                ],
            }),
            html: '',
            showModal: false,
            imgUrl: '',
            imgUrlState: null,
            blogName: '',
            blogState: null,
            root: process.env.VUE_APP_ROOT_API
        }
    },
    methods: {
        getUrl() {
            this.showModal = true;
        },
        cancelModal() {
            this.showModal = false;
        },
        handleImgUrl(evt) {
            evt.preventDefault();
            if (this.imgUrl.startsWith("https://") && this.imgUrl) {
                this.editor.commands.setImage({ src: this.imgUrl });
                this.showModal = false;
                this.imgUrl = '';
            }
            else {
                this.showModal = true;
                this.imgUrlState = false;
            }
        }, createBlog() {
            this.html = this.editor.getHTML();
            if (!this.html) {
                this.$bvToast.toast("Invalid Content, add some content..", {
                    title: "Invalid",
                    variant: "danger",
                    solid: true,
                });
                return false;
            }
            else if (!this.blogName) {
                this.$bvToast.toast("Invalid Blog name", {
                    title: "Invalid",
                    variant: "danger",
                    solid: true,
                });
                this.blogState = false;
                return false;
            }
            const data = {
                name: this.blogName,
                richTextBody: this.html,
                adminId: '9e2f484c-cab9-4e76-8c5e-b576b3d0ff89'
            }
            this.$axios
                .post(`${this.root}/blog/create `, data)
                .then((response) => {
                    if (response.data.status) {
                        this.$bvToast.toast("Blog created", {
                            title: "Success",
                            variant: "success",
                            solid: true,
                        });
                    } else {
                        this.$bvToast.toast("Couldn't create blog, try again", {
                            title: "Invalid",
                            variant: "danger",
                            solid: true,
                        });
                    }
                })
                .catch((err) => {
                    console.log(err);
                    this.$bvToast.toast("Error Occured!", {
                        title: "Error",
                        variant: "danger",
                        solid: true,
                    });
                });
        }
    },
    mounted() {
    }
}
</script>

<style>
.blog-page {
    padding: 20px;

}

.ProseMirror {
    background-color: rgb(253, 253, 253);
    border-radius: 0.5rem;
    padding: 0.75rem;
    color: black;
    outline: 1px solid black;
}

.editor-selector {
    padding: 0.75rem;
    text-align: center;
    position: -webkit-sticky;
    position: sticky;
    top: 0;
    z-index: 1;
    backdrop-filter: blur(10px);
}

img {
    max-width: 100%;
    height: auto;
    display: block;
    margin-left: auto;
    margin-right: auto;
}

pre {
    background-color: black;
    color: rgb(131, 218, 255) !important;
}
</style>