

POST http://localhost:3000/v1/admin/create 
Content-Type: application/json

{
    "name": "Mike Tyson",
    "role": "ADMIN",
    "userName": "mikeT",
    "password": "password",
    "email": "mike@mail.com"
}
###

GET http://localhost:3000/v1/admin
###

GET http://localhost:3000/v1/admin/2485ab05-d5ee-440c-a55a-44eb46922bf8

###

PATCH http://localhost:3000/v1/admin/2485ab05-d5ee-440c-a55a-44eb46922bf8
Content-Type: application/json

{
    "email": "alanR@mail.com"
}

###

DELETE http://localhost:3000/v1/admin/870ec12b-406c-4741-b55e-6edded7507ca

###

POST http://localhost:3000/v1/admin/login
Content-Type: application/json

{
    "email": "johnD@mail.com",
    "password": "123"
}

###

POST http://localhost:3000/v1/admin/filter
Content-Type: application/json

{
    "role": "ADMIN",
    "userName": "alan"
}