

POST http://localhost:3000/v1/admin/create 
Content-Type: application/json

{
    "name": "Mike Tyson",
    "role": "ADMIN",
    "userName": "mikeT",
    "password": "password",
    "email": "mike@mail.com"
}
###

GET http://localhost:3000/v1/admin
###

GET http://localhost:3000/v1/admin/2485ab05-d5ee-440c-a55a-44eb46922bf8

###

PATCH http://localhost:3000/v1/admin/f3bdbb4c-6f5c-41b5-8a62-356959f2e635
Content-Type: application/json

{
    "email": "mikey@mail.com",
    "myField":"abc"
}

###

DELETE http://localhost:3000/v1/admin/4bf08fcc-6e31-4639-8c64-a0be91e05822

###

POST http://localhost:3000/v1/admin/login
Content-Type: application/json

{
    "email": "mike@mail.com",
    "password": "password"
}

###

POST http://localhost:3000/v1/admin/filter
Content-Type: application/json

{
    "role": "ADMIN",
    "userName": "alan"
}