

POST http://localhost:3000/v1/course/add 
Content-Type: application/json

{ 
    "name":"Computer Basics",
    "description": "Some More Details",
    "courseCode": "CS103",
    "universityId": "b3399782-7f82-4ebe-bb0b-2f2e51530f85",
    "vacancy": "200",
    "adminId": "4bf08fcc-6e31-4639-8c64-a0be91e05821"
}

###

GET http://localhost:3000/v1/course?page=1&limit=3


###

PATCH http://localhost:3000/v1/course/b486f7f0-bd89-47c3-908e-47849c9ad774
Content-Type: application/json

{ 
    "name":"Data Structure and Algorithms",
    "description": "Some More Details",
    "courseCode": "CS102",
    "universityId": "6458b69d63718ff304147f09",
    "vacancy": "200"
}


###

DELETE  http://localhost:3000/v1/course/2acf5d8e-c563-46e7-97a3-9fbcf5a27e6d