

POST http://localhost:3000/v1/course/add 
Content-Type: application/json

{
    "name":"Data Analytics",
    "description": "Some More Details",
    "courseCode": "CS102",
    "universityCode": "U001",
    "vacancy": "200"
}

###

GET http://localhost:3000/v1/course


###

PATCH http://localhost:3000/v1/course/CS101
Content-Type: application/json

{
    "name": "Data Analytics V02",
    "description": "New Description Provided",
    "courseCode": "CS102",
    "universityCode": "6453aad23035870b8a00ea4b",
    "vacancy": "150"
}


###

DELETE  http://localhost:3000/v1/course/CS102