

POST http://localhost:3000/v1/university/add 
Content-Type: application/json

{
    "name": "MIT University",
    "description": "some Description",
    "universityCode": "MIT001",
    "address": "MIT, US",
    "countryId": "63d07076-bb77-461c-bcc5-dbc138162c5b",
    "adminId":"4bf08fcc-6e31-4639-8c64-a0be91e05821"
}
###


// Get Complete University
GET http://localhost:3000/v1/university?page=1&limit=2



// Get University By Country - Can add more filters on future as needed
###
GET http://localhost:3000/v1/university/filter?page=1&limit=3&countryId=c7d74bba-fb46-4f22-ab6f-373f1de5dc34

// Delete a University
###
DELETE  http://localhost:3000/v1/university/b3399782-7f82-4ebe-bb0b-2f2e51530f85


// Update a University
###
PATCH http://localhost:3000/v1/university/54e33ae8-75f9-4465-a31b-24446d34c51b
Content-Type: application/json

{
    "name": "Hardward University",
    "description": "New Description",
    "universityCode": "HU001",
    "address": "Harward University, US",
    "countryId": "c7d74bba-fb46-4f22-ab6f-373f1de5dc34"
}
