

POST http://localhost:3000/v1/user/create 
Content-Type: application/json

{
    "firstName": "John",
    "designation" :"Registered Nurse",
    "lastName" :"M",
    "email": "john@mail.com",
    "userName":"john",
    "password":"123",
    "gender":"MALE",
    "dob":"11-04-1969",
    "country":"India"
}
###

GET http://localhost:3000/v1/user
###

GET http://localhost:3000/v1/user/2023-05-03T063043.337ZJohn

###

PATCH http://localhost:3000/v1/user/6738d825-6bf6-4b49-90c3-1db4422efde8
Content-Type: application/json

{
    "country": "China",
    "email":"john@mail.com"
}

###

DELETE http://localhost:3000/v1/user/ac0b3007-6277-4918-bb5e-e3180b723b56