

POST http://localhost:3000/v1/user/create 
Content-Type: application/json

{
    "firstName": "Sara",
    "designation" :"Registered Nurse",
    "lastName" :"John",
    "email": "sara@mail.com",
    "userName":"sara",
    "password":"123",
    "gender":"FEMALE",
    "dob":"11-04-1969",
    "country":"India"
}
###

GET http://localhost:3000/v1/user
###

GET http://localhost:3000/v1/user/2023-05-02T12-08-55.500ZJames

###

PATCH http://localhost:3000/v1/user/2023-05-02T12-08-55.500ZJames
Content-Type: application/json

{
    "country": "China"
}

###

DELETE http://localhost:3000/v1/user/2023-05-02T12-08-55.500ZJames